package controller;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.Base64;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import dao.FactureDao;
import modele.Clients;
import modele.Facture;


/**
 * Servlet implementation class SendMail
 */
@WebServlet("/SendMail")
public class SendMail extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public SendMail() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		//session
		HttpSession session = request.getSession();
		
		//générer une facture
		if( request.getParameter("nom")!=null ) {
			
			String nom_user=(String) session.getAttribute("nom");
			String prenom_user=(String) session.getAttribute("prenom");
			String adresse_user=(String) session.getAttribute("adresse");
			String mail_user=(String) session.getAttribute("mail");
			
			String id_client=request.getParameter("id_client");
			String nom=request.getParameter("nom");
			String prenom=request.getParameter("prenom");
			String email=request.getParameter("email");
			String adresse=request.getParameter("adresse");
			String totalHeure=request.getParameter("totalHeure");
			String telephone=request.getParameter("tel");
			String apayer=request.getParameter("apayer");
			String datetime=request.getParameter("datetime");
			String contextPath=request.getContextPath();
			
			//creer numero de facture
			// creer token ou generer un array de byte, qu'on va ensuite tostring et encoder
			// en base64
			SecureRandom random = new SecureRandom();
			byte bytes[] = new byte[20];
			random.nextBytes(bytes);
			String token = Base64.getEncoder().encodeToString(bytes);
			
			
			//SendMail.envoi(mois, annee)
			String message1="<!DOCTYPE html>\r\n"
					+ "<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"en\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "	<title></title>\r\n"
					+ "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
					+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
					+ "	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
					+ "	<style>\r\n"
					+ "		* {\r\n"
					+ "			box-sizing: border-box;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		body {\r\n"
					+ "			margin: 0;\r\n"
					+ "			padding: 0;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		a[x-apple-data-detectors] {\r\n"
					+ "			color: inherit !important;\r\n"
					+ "			text-decoration: inherit !important;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		#MessageViewBody a {\r\n"
					+ "			color: inherit;\r\n"
					+ "			text-decoration: none;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		p {\r\n"
					+ "			line-height: inherit\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		.desktop_hide,\r\n"
					+ "		.desktop_hide table {\r\n"
					+ "			mso-hide: all;\r\n"
					+ "			display: none;\r\n"
					+ "			max-height: 0px;\r\n"
					+ "			overflow: hidden;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		@media (max-width:640px) {\r\n"
					+ "			.desktop_hide table.icons-inner {\r\n"
					+ "				display: inline-block !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner {\r\n"
					+ "				text-align: center;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner td {\r\n"
					+ "				margin: 0 auto;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.image_block img.big,\r\n"
					+ "			.row-content {\r\n"
					+ "				width: 100% !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				display: none;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.stack .column {\r\n"
					+ "				width: 100%;\r\n"
					+ "				display: block;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				min-height: 0;\r\n"
					+ "				max-height: 0;\r\n"
					+ "				max-width: 0;\r\n"
					+ "				overflow: hidden;\r\n"
					+ "				font-size: 0px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.desktop_hide,\r\n"
					+ "			.desktop_hide table {\r\n"
					+ "				display: table !important;\r\n"
					+ "				max-height: none !important;\r\n"
					+ "			}\r\n"
					+ "		}\r\n"
					+ "	</style>\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body style=\"background-color: transparent; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
					+ "	<table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: transparent;\">\r\n"
					+ "		<tbody>\r\n"
					+ "			<tr>\r\n"
					+ "				<td>\r\n"
					+ "					<table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\"><img class=\"big\" src=\"https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/top_rounded_15.png\" style=\"display: block; height: auto; border: 0; width: 620px; max-width: 100%;\" width=\"620\" alt=\"Image\" title=\"Image\"></div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/hero_bg_2.jpg'); background-position: top center; background-repeat: no-repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-left:60px;padding-right:60px;padding-top:60px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; font-family: 'Oswald', 'Lucida Sans Unicode', 'Lucida Grande', sans-serif; mso-line-height-alt: 21.6px; color: #FFFFFF; line-height: 1.8;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 61.2px;\"><span style=\"font-size:34px;\"><span style=\"font-size:34px;\">Cher </span><strong><span style=\"font-size:34px;\"><span style=\"font-size:34px;background-color:#ffffff;\"><span style=\"color:#003300;font-size:34px;background-color:#ffffff;\">&nbsp;<span style=\"color:#008000;font-size:34px;\">"+prenom+"</span>&nbsp;</span></span>,&nbsp;</span></strong></span></p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 43.2px;\"><span style=\"font-size:24px;\"><span style=\"font-size:24px;\">Votre facture</span></span></p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21.6px;\">&nbsp;</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"image_block block-2 mobile_hide\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\"><img src=\"https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/smile.png\" style=\"display: block; height: auto; border: 0; width: 64px; max-width: 100%;\" width=\"64\" alt=\"Image\" title=\"Image\"></div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block mobile_hide\" style=\"height:125px;line-height:125px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<div class=\"spacer_block mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ebebeb; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-right: 1px solid #DFDFDF; vertical-align: top; border-top: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;padding-top:20px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\"><img src=\"https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/barcode.png\" style=\"display: block; height: auto; border: 0; width: 27px; max-width: 100%;\" width=\"27\" alt=\"Image\" title=\"Image\"></div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"text_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"color:#999999;font-size:14px;\">Facture : "+token+" </span>&nbsp;</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-right: 1px solid #DFDFDF; vertical-align: top; border-top: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;padding-top:15px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\"><img src=\"https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/calendar.png\" style=\"display: block; height: auto; border: 0; width: 27px; max-width: 100%;\" width=\"27\" alt=\"Image\" title=\"Image\"></div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"text_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:10px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: left; mso-line-height-alt: 16.8px;\"><span style=\"color:#999999;font-size:14px;\">Créé le : "+datetime+" </span>&nbsp;</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"empty_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-right:0px;padding-bottom:5px;padding-left:0px;padding-top:15px;\">\r\n"
					+ "																<div></div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:5px;padding-left:40px;padding-right:40px;padding-top:15px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-family: 'Oswald', 'Lucida Sans Unicode', 'Lucida Grande', sans-serif; font-size: 12px; mso-line-height-alt: 18px; color: #56B500; line-height: 1.5;\">\r\n"
					+ "																		<p style=\"margin: 0; text-align: center; font-size: 12px; mso-line-height-alt: 36px;\"><span style=\"font-size:24px;\"><strong>Récap </strong></span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-5\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #56b500; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-right: 1px solid #519E0A; vertical-align: top; border-top: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"font-size:13px;\"><strong>Description</strong></span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-right: 1px solid #519E0A; vertical-align: top; border-top: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"font-size:13px;\"><strong>Donnée</strong></span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"font-size:13px;\"><strong>Devise</strong></span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-6\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-bottom: 0px solid #DFDFDF; border-right: 1px solid #DFDFDF; vertical-align: top; border-top: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:10px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"color:#999999;font-size:14px;\">Total d'heures effectuées</span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-bottom: 0px solid #DFDFDF; border-right: 1px solid #DFDFDF; vertical-align: top; border-top: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:10px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; text-align: center; mso-line-height-alt: 14.399999999999999px;\">"+totalHeure+"</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:10px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"color:#999999;font-size:14px;\">euros</span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-7\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #F5F5F5; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #F5F5F5; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-8\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"left\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-9\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #F5F5F5; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #F5F5F5; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-10\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"left\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-11\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-bottom: 0px solid #DFDFDF; border-right: 0px solid #DFDFDF; vertical-align: top; border-top: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-left:25px;padding-top:20px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #56B500; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; mso-line-height-alt: 16.8px;\">Méthode de paiement :</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; mso-line-height-alt: 16.8px;\"><span style=\"font-size:17px;\">PAYPAL /CB</span> <a href=\""+contextPath+"/Paiement?facture="+token+"\">Payez ici</a></p> \r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-bottom: 0px solid #DFDFDF; border-right: 0px solid #DFDFDF; vertical-align: top; border-top: 0px; border-left: 0px;\">\r\n"
					+ "													<div class=\"spacer_block\" style=\"height:25px;line-height:5px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #56B500; border-bottom: 0px solid #DFDFDF; border-left: 1px solid #DFDFDF; vertical-align: top; border-top: 0px; border-right: 0px;\">\r\n"
					+ "													<table class=\"text_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:30px;padding-left:10px;padding-right:10px;padding-top:30px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\"><span style=\"font-size:18px;\"><strong>"+apayer+" €&nbsp;</strong></span></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-12\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 20px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:5px;padding-left:40px;padding-right:40px;padding-top:15px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 18px; color: #56B500; line-height: 1.5; font-family: 'Oswald', 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">&nbsp;</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"text_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:40px;padding-right:40px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 18px; color: #555555; line-height: 1.5; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Client : "+nom+" "+prenom+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Adresse : "+adresse+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Mail : "+email+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Numéro de téléphone : "+telephone+"</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"text_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:40px;padding-right:40px;\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 18px; color: #555555; line-height: 1.5; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Entreprise : "+prenom_user+" "+nom_user+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Adresse : "+adresse_user+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Mail: "+mail_user+"</p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 18px;\">Détail des heures ici : <a href=\""+contextPath+"/DetailsHeures?facture="+token+"\">Lien heures ici</a></p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-13\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"left\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-14\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"left\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-15\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"divider_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"left\">\r\n"
					+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td class=\"divider_inner\" style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #DFDFDF;\"><span>&#8202;</span></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-16\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 10px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<div class=\"spacer_block\" style=\"height:50px;line-height:50px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-17\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #F0F0F0; background-image: url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/121/groovepaper_1.png'); background-position: top center; background-repeat: repeat;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 15px; padding-bottom: 15px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"font-family: sans-serif\">\r\n"
					+ "																	<div class style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif;\">\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; text-align: center; mso-line-height-alt: 14.399999999999999px;\"><strong>Invoices and contact © All rights reserved</strong></p>\r\n"
					+ "																		<p style=\"margin: 0; font-size: 12px; text-align: center; mso-line-height-alt: 14.399999999999999px;\">&nbsp;</p>\r\n"
					+ "																	</div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-18\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 620px;\" width=\"620\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\r\n"
					+ "																<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td class=\"alignment\" style=\"vertical-align: middle; text-align: center;\">\r\n"
					+ "																			<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
					+ "																			<!--[if !vml]><!-->\r\n"
					+ "																			<table class=\"icons-inner\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
					+ "																				<!--<![endif]-->\r\n"
					+ "																				<tr>\r\n"
					+ "																					<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"https://www.designedwithbee.com/?utm_source=editor&utm_medium=bee_pro&utm_campaign=free_footer_link\" target=\"_blank\" style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Designed with BEE\" src=\"https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/53601_510656/Signature/bee.png\" height=\"32\" width=\"34\" align=\"center\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a></td>\r\n"
					+ "																					<td style=\"font-family: Oxygen, Trebuchet MS, Helvetica, sans-serif; font-size: 15px; color: #9d9d9d; vertical-align: middle; letter-spacing: undefined; text-align: center;\"><a href=\"https://www.designedwithbee.com/?utm_source=editor&utm_medium=bee_pro&utm_campaign=free_footer_link\" target=\"_blank\" style=\"color: #9d9d9d; text-decoration: none;\">Designed with BEE</a></td>\r\n"
					+ "																				</tr>\r\n"
					+ "																			</table>\r\n"
					+ "																		</td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "				</td>\r\n"
					+ "			</tr>\r\n"
					+ "		</tbody>\r\n"
					+ "	</table><!-- End -->\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			modele.SendMail.envoi(email,message1);
			
			//GENERER LA FACTURE
			
			//Creer nouveau client
			Clients newClient=new Clients();
			
			newClient.setId_personne(Integer.valueOf(id_client));
			
			
			
			//Creer une nouvelle facture
			Facture newFacture=new Facture();
			
			newFacture.setClient(newClient);
			newFacture.setIdentifiant(token);
			newFacture.setNbr_totale_heure(totalHeure);
			newFacture.setSomme(apayer);
			
			//Creer une factureDao
			FactureDao newFactureDao=new FactureDao();
			
			newFactureDao.Create(newFacture);

		}
		response.sendRedirect(request.getContextPath() + "/Mesheures");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
